version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    working_dir: /app
    command: >
      sh -c "
      while ! nc -z db 5432; do sleep 1; done;
      uvicorn src.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend:/app
      

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
